name: CI pipeline
on:
  push:
    branches: [ master, dev ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 15.x]
    steps:
      - name: Checkout your repository under $GITHUB_WORKSPACE
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      # Runs a set of commands using the runners shell
      - name: Install packages with ci, , and finally test
        run: npm ci

      - name: run custom work in package.json with run build
        run: npm run build --if-present

      - name: syntax check over all .js files
        run: |
          for i in $(find -name '*.js' -not -path "./node_modules/*")
          do 
            node --check $i
          done

      - name: run tests
        run: npm test