name: CI pipeline
on:
  push:
    branches: 
      - master
      - dev
      - cd-pipeline
  pull_request:
    branches:
      - master
      - dev
  workflow_dispatch:
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Checkout your repository under $GITHUB_WORKSPACE
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install packages with ci, and finally test
        run: npm ci

      - name: run custom work in package.json with run build
        run: npm run build --if-present

      - name: syntax check over all .js files
        run: |
          for i in $(find -name '*.js' -not -path "./node_modules/*")
          do 
            node --check $i
          done

      - name: run tests
        run: npm test

      #- name: upload code as artifact
      #  uses: actions/upload-artifact@v2
      #  with:
      #    name: code-to-deploy
      #    path: ./

  dev-deployment:
    needs: build-and-test
    env:
      ARM_CLIENT_ID: ${{ secrets.CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.TENANT_ID }}
    runs-on: ubuntu-latest
    steps:
      - name: install terraform
        uses: hashicorp/setup-terraform@v1

      - name: deploy resources using terraform
        run: |
          cd IaC/
          terraform init
          terraform apply -var='env="dev"' -var='location="South Central US"' -auto-approve
